use std::fs;
use std::path::Path;
use std::process::Command;

use crate::diff::{self, ChangeKind, FileChange};
use crate::error::GraftError;
use crate::util::{ensure_parent_dir, IoContext};
use crate::workspace::Workspace;

pub struct MergeOpts {
    pub commit: bool,
    pub message: Option<String>,
    pub drop: bool,
    pub patch: bool,
    pub no_install: bool,
}

pub struct MergeResult {
    pub added: usize,
    pub modified: usize,
    pub deleted: usize,
    pub skipped: usize,
    pub install_ran: bool,
}

pub enum PackageManager {
    Bun,
    Pnpm,
    Npm,
    Yarn,
}

impl PackageManager {
    fn command(&self) -> &str {
        match self {
            PackageManager::Bun => "bun",
            PackageManager::Pnpm => "pnpm",
            PackageManager::Npm => "npm",
            PackageManager::Yarn => "yarn",
        }
    }
}

/// Copy changed files from the overlay back into the base directory.
/// This is the "accept these changes" operation — the reverse of fork.
pub fn merge_workspace(workspace: &Workspace, _opts: &MergeOpts) -> Result<MergeResult, GraftError> {
    let changes = diff::walk_upper(workspace)?;

    if changes.is_empty() {
        return Ok(MergeResult {
            added: 0,
            modified: 0,
            deleted: 0,
            skipped: 0,
            install_ran: false,
        });
    }

    let mut added = 0usize;
    let mut modified = 0usize;
    let mut deleted = 0usize;
    let mut skipped = 0usize;

    for change in &changes {
        // node_modules is platform-specific and regenerated by package managers
        let path_str = change.path.to_string_lossy();
        if path_str.starts_with("node_modules/") || path_str == "node_modules" {
            skipped += 1;
            continue;
        }

        match change.kind {
            ChangeKind::Added | ChangeKind::Modified => {
                let src = workspace.upper.join(&change.path);
                let dst = workspace.base.join(&change.path);

                ensure_parent_dir(&dst)?;

                fs::copy(&src, &dst).io_context(|| {
                    format!("copy {} -> {}", src.display(), dst.display())
                })?;

                match change.kind {
                    ChangeKind::Added => added += 1,
                    ChangeKind::Modified => modified += 1,
                    _ => unreachable!(),
                }
            }
            ChangeKind::Deleted => {
                let target = workspace.base.join(&change.path);
                if target.exists() {
                    fs::remove_file(&target).io_context(|| {
                        format!("remove {}", target.display())
                    })?;
                }
                deleted += 1;
            }
        }
    }

    Ok(MergeResult {
        added,
        modified,
        deleted,
        skipped,
        install_ran: false,
    })
}

/// Detect the package manager used by the workspace, if any.
/// Returns a PM only if package.json was modified AND a lockfile exists.
pub fn detect_package_manager(workspace: &Workspace) -> Option<PackageManager> {
    let upper = &workspace.upper;

    // Check if package.json was modified (exists in upper)
    if !upper.join("package.json").exists() {
        return None;
    }

    // Check for lockfiles in order of preference
    if upper.join("bun.lockb").exists() || upper.join("bun.lock").exists() {
        return Some(PackageManager::Bun);
    }
    if upper.join("pnpm-lock.yaml").exists() {
        return Some(PackageManager::Pnpm);
    }
    if upper.join("package-lock.json").exists() {
        return Some(PackageManager::Npm);
    }
    if upper.join("yarn.lock").exists() {
        return Some(PackageManager::Yarn);
    }

    None
}

/// Run the package manager's install command in the base directory.
pub fn run_install(base: &Path, pm: &PackageManager) -> Result<(), GraftError> {
    let cmd = pm.command();
    let status = Command::new(cmd)
        .arg("install")
        .current_dir(base)
        .status()
        .map_err(|e| {
            GraftError::PackageManagerFailed(format!(
                "failed to run '{cmd} install': {e}. Is {cmd} installed and on your PATH?"
            ))
        })?;

    if !status.success() {
        return Err(GraftError::PackageManagerFailed(format!(
            "'{cmd} install' exited with status {status}"
        )));
    }

    Ok(())
}

/// Generate a unified patch from workspace changes, suitable for `git apply` / `patch -p1`.
pub fn generate_patch(workspace: &Workspace, changes: &[FileChange]) -> Result<String, GraftError> {
    let mut patch = String::new();
    for change in changes {
        let diff_text = diff::generate_unified_diff(workspace, change);
        patch.push_str(&diff_text);
        if !diff_text.ends_with('\n') {
            patch.push('\n');
        }
    }
    Ok(patch)
}

/// Commit all changes in the base directory using git.
pub fn git_commit(base: &Path, message: &str) -> Result<(), GraftError> {
    if !base.join(".git").exists() {
        return Err(GraftError::GitFailed(
            "base directory is not a git repository".to_string(),
        ));
    }

    let status = Command::new("git")
        .args(["add", "-A"])
        .current_dir(base)
        .status()
        .map_err(|e| GraftError::GitFailed(format!("failed to run 'git add -A': {e}")))?;

    if !status.success() {
        return Err(GraftError::GitFailed(format!(
            "'git add -A' exited with status {status}"
        )));
    }

    let status = Command::new("git")
        .args(["commit", "-m", message])
        .current_dir(base)
        .status()
        .map_err(|e| GraftError::GitFailed(format!("failed to run 'git commit': {e}")))?;

    if !status.success() {
        return Err(GraftError::GitFailed(format!(
            "'git commit' exited with status {status}"
        )));
    }

    Ok(())
}
